### ISSUE TITLE
Can't install Pymakr plugin on ATOM due to incompatibility

### ISSUE THREAD

**Issue by mm66** [pycom/pymakr-atom#104]
Hi, 

i just installed Atom so i could use the Pymakr plugin, however when i try to install it via aAom it says that there are no available versions of the package which would be compatible with my version of Atom.

Looks like this
![image](https://user-images.githubusercontent.com/22916052/47398133-0a3eec80-d733-11e8-916d-91f690d3b081.png)

Operating system: Windows 10 Education

Atom version: 1.32.0.

Pymakr version: 1.4.4.

**Comment by RalphHogenbirk** [comment]
Hi @mm66, we've released Pymakr 1.4.5 just a few minutes ago, which is flagged with 1.32 compatibility. Try again and let me know if it woks now :)

**Comment by mm66** [comment]
The issue is resolved, thanks :)
