### ISSUE TITLE
Undocumented ctrl-f (safeboot) shortcut?

### ISSUE THREAD

**Issue by jirikrepl** [pycom/pymakr-atom#110]
Hello, after pressing ctrl-f device boots to safeboot. But this shortcut is missing in Readme.

@iwahdan88 suggested this ctrl-f shortcut to me, does Pymakr fully support it (and we're just missing it in the Readme), please? Thank you.

**Comment by RalphHogenbirk** [comment]
Shortcut has been added to the readme file in v1.4.10
