### ISSUE TITLE
Pymakr On windows Atom

### ISSUE THREAD

**Issue by obamalaolu** [pycom/pymakr-atom#123]
![Capture](https://user-images.githubusercontent.com/51482886/59449188-8b500e80-8dfe-11e9-9f6b-c252b58aa3f1.PNG)

Anyone know how to fix on windows?

**Comment by aureleq** [comment]
A workaround is to uninstall the package, and then perform a manual installation following: https://github.com/pycom/pymakr-atom/#manual-install

Edit the package.json and set the atom version to `<1.39.0` for instance, then run `npm install`

**Comment by RalphHogenbirk** [comment]
Sorry about this, we're a tad behind on the compatibility flag. Will do a release beginning of the week to fix it!

**Comment by RalphHogenbirk** [comment]
Has been fixed in v1.4.14
