### ISSUE TITLE
Pymakr 1.4.13 incompatible with Atom 1.38.2

### ISSUE THREAD

**Issue by TomBurg** [pycom/pymakr-atom#124]
I was updating pymakr plug-in to version 1.4.13 but then was told it was incompatible.
Is the problem that I updated Atom to 1.38.2 x64 ?
Do I uninstall Atom 1.38 and replace with 1.37 or is there a fix for pymakr ? (Version 1.4.14 ??)

**Operating system:** Windows 10 Home Version 1809

**Atom version:** 1.38.2

**Pymakr version:** 1.4.13

**Comment by RalphHogenbirk** [comment]
Latest version of Pymakr is 1.4.14, which was released yesterday and is compatible with 1.38 and and 1.39-beta.

**Comment by TomBurg** [comment]
Thank you, Thank You, THANK YOU!!
