### ISSUE TITLE
On changing font size in the Python console of ESP32 display

### ISSUE THREAD

**Issue by jdcrunchman** [pycom/pymakr-atom#128]
(Hi! 👋  Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

I'm visually challenged,  and need to increase the font size in the ESP32 console size in the Atom IDE.    Although the general IDE does have font control,   anything I do there,  is not reflected in the console.
Please Email me at jdcrunchman@gmail.com after you reply,

The MyPakr settings has no way to do that.  

## What are the steps to reproduce this issue?
1.   No way to change font size in the ESP32 Python Console displayed at bottom of screen.
2.
3.

## What happens?

Nothing

## What were you expecting to happen?

Font change so I can see the console,   I'm visually impaired.

## Any logs, error output, etc?
*(If it’s long, please paste to https://gist.github.com and insert the link here)*
No logs

## Any other comments?
I just need to be able to change the font size of the ESP32 console,  no way I can find that does this,   If this feature exists,  it is hidden vert well,  and should be put in the readme.

## What versions of software are you using?
1.4.14

**Operating system:**
Mac OS - 10.13.6

**Atom version:**
1.38.2 X64

**Pymakr version:**
1.4.14

**Comment by pedroknup** [comment]
That's now possible with Pymakr v2
