### ISSUE TITLE
Failed to activate the pymakr package in windows 10

### ISSUE THREAD

**Issue by choc70** [pycom/pymakr-atom#129]
was compiled against a different Node.js version using

NODE_MODULE_VERSION 57. This version of Node.js requires

NODE_MODULE_VERSION 64. Please try re-compiling or re-installing

the module (for instance, using npm rebuild or npm install).

**Comment by jaketeater** [comment]
seems to be a duplicate of #127 

For me, the work around was to downgrade Atom to 1.38.2

**Comment by Oct-opus** [comment]
Same here, 
Downgrading to 1.38.2 does fix it but you have to disable Atom auto update.
It's not rely a fix, just a temporary solution ...

**Comment by sophiekovalevsky** [comment]
I can confirm that I had this bug. Before compiling again the package, I tried to uninstall pymark, and relaunch atom, it works. 

Atom version: 1.39.1
