### ISSUE TITLE
Pysense and pytrack failed to upload with compression 

### ISSUE THREAD

**Issue by AbrehetIot** [pycom/pymakr-atom#133]
Hello
I am not able to upload anything to pysense and pytrack. The problem is, it stops uploading when it reaches some steps **with compression.** Please look the screenshot below how it stops uploading. 
![image](https://user-images.githubusercontent.com/50961011/64105444-8e5ff880-cd76-11e9-85c0-d26a8c35a132.png)

**Comment by RalphHogenbirk** [comment]
Hi @AbrehetIot, very likely your board doesn't support compression. It only works for firmware 1.20 and up. In global settings, disable 'fast upload'. De description of that setting will give you more info :)

**Comment by AbrehetIot** [comment]
Thanks more dear@RalphHogenbirk, it is solved now.

**Comment by bkomac** [comment]
Yea, on ESP8266 this defiantly does the trick. Tnx!

`"fast_upload": false`
