### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\pymakr/lib/snippets/...

### ISSUE THREAD

**Issue by basukisu2109** [pycom/pymakr-atom#135]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 1.4.16

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\User\.atom\packages\pymakr/lib/snippets/wifi-simple.py'

```
At fs.js:143

Error: ENOENT: no such file or directory, open 'C:\Users\User\.atom\packages\pymakr/lib/snippets/wifi-simple.py'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:483:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:563:29)
    at Snippets.list (/packages/pymakr/lib/board/snippets.js:58:26)
    at /packages/pymakr/lib/board/snippets.js:34:10)
    at /packages/pymakr/lib/pymakr.js:77:21)
    at /packages/pymakr/lib/main.js:40:24
    at /packages/pymakr/lib/main/settings-wrapper.js:63:7
    at /packages/pymakr/lib/main/settings-wrapper.js:187:19
    at /packages/pymakr/lib/connections/pyserial.js:158:13
    at FSReqWrap.oncomplete (fs.js:169:20)
```

### Commands

```
```

### Non-Core Packages

```
pymakr 1.4.16 
```

**Comment by RalphHogenbirk** [comment]
Sorry for the late reply, but this has very likely been patched in the latest version. Root cause of this is unknown though, because the file 'C:\Users\User\.atom\packages\pymakr/lib/snippets/wifi-simple.py' should definitely exist. I don't know why it would be missing on your system. Definitely try to re install pymakr as well
