### ISSUE TITLE
Can't find upload button, global settings, more 

### ISSUE THREAD

**Issue by Gabicac** [pycom/pymakr-atom#139]
I can't find the upload button so I can't upload the code to lopy. I think the problem is with PYMAKR because I can't uninstall (press the uninstall button but doesn't work) and the pymakr version doesn't show. 
A few days, I used without problems, and I don't know if update automatically and this new version has problem.

Thanks

**Comment by elmasria** [comment]
Hello @Gabicac, please try to remove the whole **pymakr** package, then install the latest **1.4.17**, see if that solves the issue.
