### ISSUE TITLE
Reconnect button first click not working

### ISSUE THREAD

**Issue by danieleparazza** [pycom/pymakr-atom#15]
To reproduce:
Open the console and make sure you're correctly connected using serial port;
press "reconnect" button and wait for the error message (it will appear); 
now click on the console to retry, or click "connect". It will connect instantly

**Comment by RalphHogenbirk** [comment]
I got to reproduce this, but only with telnet, not with serial. I gave the board a little bit more time to actually disconnect before trying to reconnect, which fixed the issue. I'll push the fix to develop later today. It'll be in the next release.

**Comment by RalphHogenbirk** [comment]
There you go, that should fix it. Try the code on develop to see if it works properly for you.

**Comment by theRealBugger** [comment]
There's a problem installing from develop branch
[npm-debug.log.txt](https://github.com/pycom/pymakr-atom/files/978641/npm-debug.log.txt)

**Comment by RalphHogenbirk** [comment]
Sorry about that, font-awesome lib had a wrong version number in package.json. Fixed it just now on develop (02b9cb7)

**Comment by theRealBugger** [comment]
Nope, problem is still there. How can I help you further?

**Comment by RalphHogenbirk** [comment]
Really, exactly the same error report (No compatible version found: font-awesome@^4.7.2)? Make sure you removed node_modules and try apm install or npm install again. If that doesn't help feel free to post the new npm log again so I can see what's going on.

**Comment by theRealBugger** [comment]
Sorry, I installed succesfully. I meant the OP error is still there

**Comment by RalphHogenbirk** [comment]
Stange, on my boards it works. You can try to increase the timeout in lib/connections/pytelnet.js:72 and see if that helps. Maybe 200ms is not enough for all setups.

**Comment by RalphHogenbirk** [comment]
@theRealBugger do you still have issues with this? Or did an increased timeout work for you?

**Comment by theRealBugger** [comment]
I have not tried yet but the problem is persisting

**Comment by theRealBugger** [comment]
I changed timeout to 500ms but nothing is changed (I'm using v1.0.0 now). It doesn't look like a timing issue. It's like a variable is not toggled (if i double click the button very quickly the connection works)

**Comment by RalphHogenbirk** [comment]
Old issue, I now, but this should be solved with the latest version, right? Have not heard anyone with this issue since. If still have it, please re-open the issue, but for now I'll close it.
