### ISSUE TITLE
why wouldn't install pymakr on the Atom?

### ISSUE THREAD

**Issue by denysorozco** [pycom/pymakr-atom#152]
I can't install Atom ide on my windows 7 x64 and download this portable: https://github.com/atom/atom/releases/tag/v1.5.3 but it wouldn't install pymakr which I use with pycom's LoPy. whats going on here?

**Comment by pedroknup** [comment]
Hi Deny. That portable version is currently not supportable by Pymakr. Please try a newer Atom version (1.35.0 at least) with the latest Pymakr version.
