### ISSUE TITLE
pymakr plugin not working with atom ide

### ISSUE THREAD

**Issue by ssummers-lime** [pycom/pymakr-atom#223]
Atom version 1.52.0
pmakr version 2.1.5
The REPL console does not load with this version combination.

**Comment by ssummers-lime** [comment]
I installed Atom version 1.51.0 and the console loaded correctly. So something that Atom did from 1.51 to 1.52 broke pymakr.

**Comment by bagaar-tech** [comment]
I observed the same issue and the same fix as @ssummers-lime .
Issue might be related to other issues reported in the past, because I noticed following errors:

Error while loading serialport library 
Error Could not locate the bindings file.

**Comment by ssummers-lime** [comment]
v1.52.0 is now working with v2.1.6
