### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, mkdir '~/Documents/FYP/LoPy4/micropython-lib-m...

### ISSUE THREAD

**Issue by dillontankj** [pycom/pymakr-atom#237]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.0.1
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 2.1.8

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, mkdir '/Users/dillon/Documents/FYP/LoPy4/micropython-lib-master/datetime'

```
At fs.js:126

Error: ENOENT: no such file or directory, mkdir '/Users/dillon/Documents/FYP/LoPy4/micropython-lib-master/datetime'
    at Object.mkdirSync (fs.js:764:3)
    at Utils.ensureDirectoryExistence (/packages/pymakr/lib/helpers/utils.js:89:8)
    at Utils.ensureFileDirectoryExistence (/packages/pymakr/lib/helpers/utils.js:82:17)
    at /packages/pymakr/lib/features/sync/sync.js:445:21
    at /packages/pymakr/lib/board/shell.js:285:9
```

### Commands

```
```

### Non-Core Packages

```
pymakr 2.1.8 
```

**Comment by elmasria** [comment]
HI @dillontankj 

Did you get this issue when you were trying to download device files on your pc? do you have subfolders on the device?

Best Regards,
Ahmad El Masri
