### ISSUE TITLE
Uncaught TypeError: atom.confirm(...).then is not a function

### ISSUE THREAD

**Issue by jthompson-ceres** [pycom/pymakr-atom#238]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.7
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 2.1.8

### Stack Trace

Uncaught TypeError: atom.confirm(...).then is not a function

```
At /Users/joshua/.atom/packages/pymakr/lib/features/sync/sync.js:386

TypeError: atom.confirm(...).then is not a function
    at /packages/pymakr/lib/features/sync/sync.js:386:12
```

### Commands

```
```

### Non-Core Packages

```
pymakr 2.1.8 
```

**Comment by elmasria** [comment]
Hello @jthompson-ceres,

Please note that a new version is available that solves the above issue.

**Comment by JoshuaBThompson** [comment]
@elmasria still happening on atom 1.55.0 x64 (mac osx)
