### ISSUE TITLE
terminal doesn't show

### ISSUE THREAD

**Issue by gasparlopes98** [pycom/pymakr-atom#242]

**Comment by elmasria** [comment]
Can you please give more information. What OS you are using, which version of Atom you are using, and which version of Pymakr?

**Comment by gasparlopes98** [comment]
I'm using Atom 1.54.0, the latest version of Pymark and running on Windows 10. 
I think it was the last update of Pymark that cause this issue, befaure that it was all running.

**Comment by gasparlopes98** [comment]
RESOLVED:
Had to delete Pymakr from .atom\packages and reinstall it. I don't know why, on Atom was showing that Pymakr was installed but didn't recognize it, and when i clicked to uninstall nothing happen.
