### ISSUE TITLE
can't connect pyboard in vscode with pymkr

### ISSUE THREAD

**Issue by Irvingao** [pycom/pymakr-atom#243]
## What happens?
I used pymkr running well for long time. But A few days before, i found i can't connect with any pyboards in vscode and i didn't change anything in global setting.
I had already connected pyboard sucessfully:
![image](https://user-images.githubusercontent.com/58903762/107873541-3d05e380-6eee-11eb-9b13-46b6ba1a223e.png)

Here is my pymkr problem:

![image](https://user-images.githubusercontent.com/58903762/107873456-a9ccae00-6eed-11eb-9b3e-b88ee51f8e30.png)

But i can connect pyboards with putty successfully and it works well, it means it's not my board or port problems.

![image](https://user-images.githubusercontent.com/58903762/107873441-8f92d000-6eed-11eb-8d9a-5405b3acee02.png)

## What were you expecting to happen?
I want to know how to fix it and what's the possible problem of pymkr? 

## Any logs, error output, etc?
*(If it’s long, please paste to https://gist.github.com and insert the link here)*

## Any other comments?
this is my Global setting as same as before when it works well:
`{
	"address": "COM1",
	"username": "micro",
	"password": "python",
	"sync_folder": "pyb-controller_robot",
	"open_on_start": true,
	"sync_file_types": "py,txt,log,json,xml,html,js,css,mpy",
	"ctrl_c_on_connect": false,
	"safe_boot_on_upload": false,
	"py_ignore": [
		"pymakr.conf",
		".vscode",
		".gitignore",
		".git",
		"project.pymakr",
		"env",
		"venv"
	],
	"fast_upload": false,
	"sync_all_file_types": false,
	"auto_connect": false,
	"autoconnect_comport_manufacturers": [
		"Pycom",
		"Pycom Ltd.",
		"FTDI",
		"Microsoft",
		"Microchip Technology, Inc."
	]
}`

## What versions of software are you using?

**Operating system:**
Windows
**Atom version:**
vscode
**Pymakr version:**
lastest

**I'm so appreciate if u can help to slove the problems. Thank you!**

**Comment by elmasria** [comment]
@Irvingao , Can you please update us with your Windows version, Pymakr Version (is it 2.1.12?), and Atom version.
