### ISSUE TITLE
Troubles installing Pymakr with Atom

### ISSUE THREAD

**Issue by iamlao** [pycom/pymakr-atom#257]
Hello, 

I recently tried to update Pymakr with Atom and didn't manage to do it.
I uninstalled Pymakr and then It was impossible to reinstall it.
The installation just doesn't start. 

### Versions 
Atom : 1.57.0
Pymakr : 2.1.13

Have you already had this ?

**Comment by elmasria** [comment]
HI @iamlao 
please check this (https://github.com/pycom/pymakr-atom/issues/256)

if you are not using WIndows OS, Please provide me with more details so we can support your case.

**Comment by iamlao** [comment]
@elmasria 
Thank you 
I will check 
Have a nice day

**Comment by iamlao** [comment]
@elmasria 
It works 
Thank you very much
