### ISSUE TITLE
Updating to “pymakr@2.1.13” failed

### ISSUE THREAD

**Issue by aleroise** [pycom/pymakr-atom#262]
Using MacOs BigSur 11.3, after installing Atom version 1.57.0 x64, updating to “pymakr@2.1.13” failed.

**Output :**

@serialport/bindings@8.0.8 install /private/var/folders/hz/xjbzbplx3fj72njqf6fw_s540000gn/T/apm-install-dir-2021528-1853-137sw22.spsy/node_modules/pymakr/node_modules/@serialport/bindings
prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated parser-cctalk@1.0.2: reanmed to @serialport/parser-cctalk
npm WARN deprecated parser-byte-length@1.0.2: renamed to @serialport/parser-byte-length
npm WARN deprecated parser-readline@1.0.2: reanmed to @serialport/parser-readline
npm WARN deprecated parser-ready@1.0.2: reanmed to @serialport/parser-ready
npm WARN deprecated parser-delimiter@1.0.2: reanmed to @serialport/parser-delimiter
npm WARN deprecated parser-regex@1.0.2: reanmed to @serialport/parser-regex
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
prebuild-install WARN install No prebuilt binaries found (target=9.4.4 runtime=electron arch=x64 libc= platform=darwin)
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/private/var/folders/hz/xjbzbplx3fj72njqf6fw_s540000gn/T/AppTranslocation/979D53B8-7073-47D3-8516-F17CB36E702B/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 20.4.0
gyp ERR! command "/private/var/folders/hz/xjbzbplx3fj72njqf6fw_s540000gn/T/AppTranslocation/979D53B8-7073-47D3-8516-F17CB36E702B/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/hz/xjbzbplx3fj72njqf6fw_s540000gn/T/AppTranslocation/979D53B8-7073-47D3-8516-F17CB36E702B/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/hz/xjbzbplx3fj72njqf6fw_s540000gn/T/apm-install-dir-2021528-1853-137sw22.spsy/node_modules/pymakr/node_modules/@serialport/bindings
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN notsup Unsupported engine for pymakr@2.1.13: wanted: {"atom":">=1.41.0","node":">=6.3.0 <=7.0.0"} (current: {"node":"12.14.1","npm":"6.14.13"})
npm WARN notsup Not compatible with your version of node/npm: pymakr@2.1.13
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/hz/xjbzbplx3fj72njqf6fw_s540000gn/T/apm-install-dir-2021528-1853-137sw22.spsy/package.json'
npm WARN apm-install-dir-2021528-1853-137sw22.spsy No description
npm WARN apm-install-dir-2021528-1853-137sw22.spsy No repository field.
npm WARN apm-install-dir-2021528-1853-137sw22.spsy No README data
npm WARN apm-install-dir-2021528-1853-137sw22.spsy No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@8.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @serialport/bindings@8.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/remy/.atom/.apm/_logs/2021-06-28T15_19_29_044Z-debug.log

**Comment by elmasria** [comment]
Hello @aleroise,

Thank you for your feedback, please take a look at the below issue (on the last 2 comments) should fix the bug you are facing.

https://github.com/pycom/pymakr-atom/issues/251#issuecomment-842253206
https://github.com/pycom/pymakr-atom/issues/251#issuecomment-866853548

Best Regards,
Ahmad EL Masri
