### ISSUE TITLE
How to increase font size of atom pymakr console/REPL window?

### ISSUE THREAD

**Issue by rafi021** [pycom/pymakr-atom#29]
Hi Pycom team,
Need help. how to increase font size/custom font on atom pymakr console/REPL window??

**Comment by RalphHogenbirk** [comment]
Sorry for the late reply. At the moment, this is not possible. I've added it to the task list.

**Comment by rolandvs** [comment]
Any progress?

**Comment by pedroknup** [comment]
That's now possible since Pymakr 2.0
