### ISSUE TITLE
i can't install pymakr

### ISSUE THREAD

**Issue by valentinarivas** [pycom/pymakr-atom#298]
> @serialport/bindings-cpp@10.7.0 install /tmp/apm-install-dir-202231-20938-1bqgj32.r3qn/node_modules/pymakr/node_modules/@serialport/bindings-cpp
> node-gyp-build

make: se entra en el directorio '/tmp/apm-install-dir-202231-20938-1bqgj32.r3qn/node_modules/pymakr/node_modules/@serialport/bindings-cpp/build'
  CXX(target) Release/obj.target/bindings/src/serialport.o
  CXX(target) Release/obj.target/bindings/src/serialport_unix.o
  CXX(target) Release/obj.target/bindings/src/poller.o
make: se sale del directorio '/tmp/apm-install-dir-202231-20938-1bqgj32.r3qn/node_modules/pymakr/node_modules/@serialport/bindings-cpp/build'

npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated parser-delimiter@1.0.2: reanmed to @serialport/parser-delimiter
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated parser-byte-length@1.0.2: renamed to @serialport/parser-byte-length
npm WARN deprecated parser-cctalk@1.0.2: reanmed to @serialport/parser-cctalk
npm WARN deprecated parser-readline@1.0.2: reanmed to @serialport/parser-readline
npm WARN deprecated parser-ready@1.0.2: reanmed to @serialport/parser-ready
npm WARN deprecated parser-regex@1.0.2: reanmed to @serialport/parser-regex
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
../src/poller.cpp: In static member function ‘static Napi::Object Poller::Init(Napi::Env, Napi::Object)’:
../src/poller.cpp:108:7: error: ‘class Napi::Env’ has no member named ‘SetInstanceData’
  108 |   env.SetInstanceData<Napi::FunctionReference>(constructor);
      |       ^~~~~~~~~~~~~~~
../src/poller.cpp:108:46: error: expected primary-expression before ‘>’ token
  108 |   env.SetInstanceData<Napi::FunctionReference>(constructor);
      |                                              ^
../src/poller.cpp: In static member function ‘static Napi::Value Poller::New(const Napi::CallbackInfo&)’:
../src/poller.cpp:127:53: error: ‘class Napi::Env’ has no member named ‘GetInstanceData’
  127 |   Napi::FunctionReference* constructor = info.Env().GetInstanceData<Napi::FunctionReference>();
      |                                                     ^~~~~~~~~~~~~~~
../src/poller.cpp:127:92: error: expected primary-expression before ‘>’ token
  127 |   Napi::FunctionReference* constructor = info.Env().GetInstanceData<Napi::FunctionReference>();
      |                                                                                            ^
../src/poller.cpp:127:94: error: expected primary-expression before ‘)’ token
  127 |   Napi::FunctionReference* constructor = info.Env().GetInstanceData<Napi::FunctionReference>();
      |                                                                                              ^
make: *** [bindings.target.mk:116: Release/obj.target/bindings/src/poller.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/tmp/apm-install-dir-202231-20938-1bqgj32.r3qn/node_modules/pymakr/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.13.0-39-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/tmp/apm-install-dir-202231-20938-1bqgj32.r3qn/node_modules/pymakr/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-202231-20938-1bqgj32.r3qn/node_modules/pymakr/node_modules/@serialport/bindings-cpp
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
npm WARN notsup Unsupported engine for @serialport/bindings-cpp@10.7.0: wanted: {"node":">=12.17.0 <13.0 || >=14.0.0"} (current: {"node":"12.14.1","npm":"6.14.13"})
npm WARN notsup Not compatible with your version of node/npm: @serialport/bindings-cpp@10.7.0
npm WARN notsup Unsupported engine for @serialport/bindings-interface@1.2.1: wanted: {"node":"^12.22 || ^14.13 || >=16"} (current: {"node":"12.14.1","npm":"6.14.13"})
npm WARN notsup Not compatible with your version of node/npm: @serialport/bindings-interface@1.2.1
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-202231-20938-1bqgj32.r3qn/package.json'
npm WARN apm-install-dir-202231-20938-1bqgj32.r3qn No description
npm WARN apm-install-dir-202231-20938-1bqgj32.r3qn No repository field.
npm WARN apm-install-dir-202231-20938-1bqgj32.r3qn No README data
npm WARN apm-install-dir-202231-20938-1bqgj32.r3qn No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings-cpp@10.7.0 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @serialport/bindings-cpp@10.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/valentina/.atom/.apm/_logs/2022-04-01T16_55_51_832Z-debug.log

**Comment by jakobrosenberg** [comment]
Thanks for creating the issue. This should be fixed in `2.3.7`.
