### ISSUE TITLE
Does not detect UM Feather-S3

### ISSUE THREAD

**Issue by DandrewsDev** [pycom/pymakr-atom#312]
## What are the steps to reproduce this issue?
1. Open atom with board already attached
2. Click connect device

## What happens?
There are no devices listed even though on is connected and working. 

## What were you expecting to happen?
The device to be listed and selectable.

## Any logs, error output, etc?
"No devices detected on USB"

## Any other comments?
The device is connected and I can get a repl connection via terminal. 

/dev/cu.usbmodem_ts3_1
Connecting via screen -port /dev/cu.usbmodem_ts3_1 115200 
Works great.

## What versions of software are you using?

**Operating system:**
Mac OS 12.3

**Atom version:**
1.60.0

**Pymakr version:**
2.3.7

**Board version**
(sysname='esp32', nodename='esp32', release='1.18.0', version='v1.18 on 2022-04-07', machine='FeatherS3 with ESP32-S3')

**Comment by jakobrosenberg** [comment]
Hi @DandrewsDev, you will have to update the plugin config to accommodate your device.

![image](https://user-images.githubusercontent.com/4153004/162140346-b9fb532c-8bc0-41c1-9cc1-e85b5ccd92fa.png)

**Comment by DandrewsDev** [comment]
Adding Unexpected Maker to the list of manufactures fixed it. I should have seen that config. Thank you.
