### ISSUE TITLE
Cannot install Pymakr 2.3.7 package in Atom 1.60.0 x64 

### ISSUE THREAD

**Issue by Ridgeglider** [pycom/pymakr-atom#314]
(Please help: Cannot install pymakr plugin to Atom when using the normal Install Package >>> Pymakr

Error:
Installing “pymakr@2.3.7” failed.Hide output…

npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://www.atom.io/api/packages/pymakr/versions/2.3.7/tarball

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HShar\.atom\.apm\_logs\2022-04-24T23_07_54_548Z-debug.log

Win 10

Atom 1.60.0 x64
Pymakr version 2.3.7
[2022-04-24T23_16_51_404Z-debug.log](https://github.com/pycom/pymakr-atom/files/8551869/2022-04-24T23_16_51_404Z-debug.log)

**Comment by jakobrosenberg** [comment]
Closing in favor of https://github.com/pycom/pymakr-atom/issues/313
