### ISSUE TITLE
Sync to pysense

### ISSUE THREAD

**Issue by dbrgn** [pycom/pymakr-atom#32]
For me, syncing to the pysense (device /dev/ttyACM0) does not seem to work. Syncing to the expansion board (/dev/ttyUSB0) works though.

Is this a bug or a limitation of the pysense?

**Comment by RalphHogenbirk** [comment]
It should work, but if you are running lots of code like I was running on the pysense (complete pysense library + pybytes lib) then you run into trouble with memory usage. The error reporting in that case is not working properly in that case and will report 'undefined' as a reason for the failed sync. 

If this is the case, try syncing after doing a safe boot, or without loading any libraries in the boot or main file. There is not a good solution for this yet, unfortunately. You could use FTP for this project.
