### ISSUE TITLE
No response during plugin installation

### ISSUE THREAD

**Issue by AgustinPelaez** [pycom/pymakr-atom#41]
After clicking on Pymakr plugin "Install" button, there's no feedback to know if the installation was successful or not - Install button stays in "loading" mode.

OSX: 10.13
Pymakr: 1.1.1
![image](https://user-images.githubusercontent.com/884487/30500039-508b99a8-9a22-11e7-8d82-cf42e87f9ba0.png)

**Comment by sdaniel55** [comment]
Hi @AgustinPelaez, has this been resolved? I'll close this for now since I haven't experienced any problems with it. Feel free to reopen it if it still doesn't work!
