### ISSUE TITLE
Error: Writing to COM port (GetOverlappedResult): Operation aborted)

### ISSUE THREAD

**Issue by jhoguaman** [pycom/pymakr-atom#45]
I updated Atom (1.21.1) and Pymakr (1.2.0). The option Run in to REPL console works good. But when I want synchronize (Upload) a file, I get this error:
 
Error: Writing to COM port (GetOverlappedResult): Operation aborted
Failed to read project status, uploading all files

When I worked with previous versions  I didn't have any problem.

**Comment by RalphHogenbirk** [comment]
Hi @jhoguaman, sorry to hear about this error. Looking at it, it should be a windows only issue. I didn't get it on my own windows machine when testing, but I'll try to reproduce it. Can you send me the versions you are using? (output of `apm --version`) 

I'm on a short trip outside the office until Monday, so I'll have a look at it first thing on tuesday. Hope that's not a problem for you. You could temporarily switch back to an older version for now, or use visual studio code

**Comment by jhoguaman** [comment]
Hi @RalphHogenbirk, Do you refer to this?

![image](https://user-images.githubusercontent.com/28904263/32110829-34edb4cc-bafe-11e7-9505-ba1fac6d188c.png)

Thanks for your response friend..!!

**Comment by mkrummenacher** [comment]
I can confirm the problem on Windows 10 x64. Before the update it worked with expansion board and PySense. Now it's working if the LoPy is mounted on the PySense board, but not on the expansion board.

**Comment by RalphHogenbirk** [comment]
Thanks for the extra info @mkrummenacher, that will help me narrow the problem down! I'll keep you guys up to date

**Comment by danicampora** [comment]
@Smeedy thanks for the report. There is an issue with the latest firmware that is causing this. We are solving it and a new firmware release will be out within 48hrs.

**Comment by ThomasBastien** [comment]
Is the new firmware available?

**Comment by ThomasBastien** [comment]
The issue comes from Pymakr plugin for ATOM, with the release 1.1.5 it works.

**Comment by agallo** [comment]
This is happening on Windows 7, Atom 1.22.1, Pymakr 1.2.1

**Comment by mkrummenacher** [comment]
I have updated the firmware to 1.10.1.b1 but still have the same problem:
![grafik](https://user-images.githubusercontent.com/33263596/33078568-5425b180-ced3-11e7-9855-ba9e1a832800.png)

Windows 10 x64
Atom 1.22.1
Pymakr 1.2.1

Only uploading does not work, "show firmware version" and "run" are working.

**Comment by shailes** [comment]
I also have precisely the same problem (and have been having it for the past 3 weeks or so, with different versions of Pymakr and the firmware):

Current configuration:
LoPy
Firmware 1.10.1.b1
Windows 10 x64
Atom 1.22.1
Pymakr 1.2.1

Upload doesn't work, but run does: 
> Failed to connect (Error: Writing to COM port (GetOverlappedResult): Operation aborted). Click here to try again.

**Comment by pkilcoyne** [comment]
I'm seeing the same issue, uploads work fine from pysense board but on the expansion board I'm getting the above error. I'm on a windows 10 machine running Atom 1.22.1 and Pymakr 1.2.1

Has this been resolved yet or is there a work around?

Thanks,

Paul

**Comment by RalphHogenbirk** [comment]
Pymakr v1.2.2 has now been released which should fix this bug! Let me know if it solves your issues

**Comment by agallo** [comment]
Windows 7 64-bit, Atom 1.22.1, Pymakr v1.2.2 -- working so far. 

Thanks for the fix.

**Comment by mkrummenacher** [comment]
I can confirm that it's working with the new Version. Windows 10 1709 x64, Atom 1.22.1, Pymakr 1.2.2.

Thank you for your help!

**Comment by SpoofEx** [comment]
It seems I  have a similar issue uploading a project:
![afbeelding](https://user-images.githubusercontent.com/35561405/35092045-7f3193f6-fc3e-11e7-8b10-0a5fb9bf1c5c.png)

when i remove the 036e59.....json file I get the following error:
![afbeelding](https://user-images.githubusercontent.com/35561405/35092198-efb1dcda-fc3e-11e7-9b59-b30d4667d69f.png)

Current configuration:
windows 10 1709 16299.125
atom 1.23.3
Pymakr 1.2.27

I noticed I had to limit the baud rate when I initially flashed the .bin file to the ESP32 otherwise it failed.
