### ISSUE TITLE
Uploading to the /sd instead of the /flash

### ISSUE THREAD

**Issue by rolandvs** [pycom/pymakr-atom#47]
Somehow it seems NOT possible to use atom/pymakr to upload scripts to the external /sd instead of the /flash.

Is there a trick to do this?

I have a modest set of files, but the lopy has no storage space left. So I need to transfer the lot to the external SD.

So how to set the sync folder?

**Comment by RalphHogenbirk** [comment]
No Roland, this is not possible right now. Could be a nice new feature though, I'll do a test with it soon. But since Pymakr uploads through the REPL, which runs in the /flash folder, I'm not sure it has access to the /flash folder. I suggest you use FTP to upload your files for now.
