### ISSUE TITLE
Excessive CPU used when PyMakr console maximised

### ISSUE THREAD

**Issue by kompleteb** [pycom/pymakr-atom#57]
I have recently converted across to the Atom Pymakr plugin and found an issue with excessive CPU being consumed by the plugin when the console window is maximised (i.e. the corporal stripe is pointing down). Here is a screenshot of my task manager under Windows 10 64-bit when the issue is seen.

![image](https://user-images.githubusercontent.com/35202636/34654400-e9191bb8-f45f-11e7-8287-f328922cd1c0.png)

The CPU is always above 30% (on an Intel i7 3.2Ghz)). The state of Atom with pymakr console maximised is pictured below:

![image](https://user-images.githubusercontent.com/35202636/34654417-2cf9f71c-f460-11e7-843c-f803d9eb8c68.png)

However when the window is minimised....

![image](https://user-images.githubusercontent.com/35202636/34654425-41501b7e-f460-11e7-9c91-4b8dc091327c.png)

the CPU usage is as expected...

![image](https://user-images.githubusercontent.com/35202636/34654438-5cffdf62-f460-11e7-9d12-951f4acf1207.png)

Any ideas as to the cause? Everything works fine - its just really inefficient and my CPU fan drives me nuts after a while :)

**Comment by RalphHogenbirk** [comment]
Hey @kompleteb, that's strange, never noticed that, will test it when I get my hands on a windows machine. On mac the atom cpu usage stays unchanged with the console open or closed. Can't think of any reason why this would happen, at least not on nodejs level.

Does the CPU also increase when connecting over IP?

**Comment by kompleteb** [comment]
@RalphHogenbirk, good question...and the answer is:

CPU usage is normal when connecting over IP.  

Thanks for the tip.  Perhaps the serial routines in Nodejs are polling the input buffer too aggressively?

**Comment by kompleteb** [comment]
and the peace and quiet of a silent fan is bliss!

**Comment by RalphHogenbirk** [comment]
That's good to know, a serial routine polling too often makes sense. I see that the implementation of the serialport lib for windows has a lot of differences with the osx version, so the issue could be in there. Will put it on my list to look at. Curious to see if there are more people with the issue as well.
