### ISSUE TITLE
Uncaught TypeError: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by mnelson920** [pycom/pymakr-atom#79]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 17.10
**Thrown From**: [pymakr](https://github.com/pycom/pymakr-atom) package 1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'error' of undefined

```
At /home/mark/.atom/packages/pymakr/lib/board/sync.js:197

TypeError: Cannot read property 'error' of undefined
    at /packages/pymakr/lib/board/sync.js:197:22
    at Pyboard.waiting_for_cb (/packages/pymakr/lib/board/pyboard.js:192:11)
    at /packages/pymakr/lib/board/pyboard.js:481:17
```

### Commands

```
     -2:18.3.0 core:confirm (input.hidden-input)
 14x -1:30 core:backspace (input.hidden-input)
     -1:17.8.0 application:open-folder (input.hidden-input)
```

### Non-Core Packages

```
pymakr 1.3.0 
```

**Comment by RalphHogenbirk** [comment]
Thanks for reporting. This is a small bug in the code that handles an error during initialisation of the upload procedure. I fixed it and will put it in the next debug release.
The actual cause of the error is unknown though. Was this a one-time occurance, or does it keep happening every time you try to upload?

**Comment by mnelson920** [comment]
Thanks looking into it. Sorry, I can't say if this one of thing or not. After that error I tried again on a different PC.

**Comment by wewerucha** [comment]
Hey,I discovered this err too. 
@RalphHogenbirk > yes it happen every time, could you please upload some manual repair solution? 

Thx

**Comment by jirikrepl** [comment]
Hi Ralph, thanks for answer. 
For me it happens maybe like every 20th code upload to device.

**Comment by RalphHogenbirk** [comment]
I've pushed release 1.3.1 that has a bugfix in the error handling. It might not solve whatever is causing the upload to fail, but at least you will get a proper error message and allow you to retry the upload.
