### ISSUE TITLE
Uncaught TypeError: this.terminal.writeln_and_prompt is not a function

### ISSUE THREAD

**Issue by danicampora** [pycom/pymakr-atom#8]
[Enter steps to reproduce:]

1. Create a new untiled file.
2. Write at leas 1 line of code (e.g. print('Test'))
3. On the Pymakr console click on run without saving the file.

I think that if the file is not created yet it should prompt you into saving the file, otherwise it should save the file automatically and then run it.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [Pymakr](https://github.com/pycom/pymakr-atom) package 0.9.3

### Stack Trace

Uncaught TypeError: this.terminal.writeln_and_prompt is not a function

```
At /Users/danicampora/.atom/packages/Pymakr/lib/pymakr-view.js:263

TypeError: this.terminal.writeln_and_prompt is not a function
    at onerror (/packages/Pymakr/lib/pymakr-view.js:263:23)
    at PymakrView.getCurrentFile (/packages/Pymakr/lib/pymakr-view.js:340:11)
    at PymakrView.run (/packages/Pymakr/lib/pymakr-view.js:254:12)
    at HTMLButtonElement.PymakrView.button_run.onclick (/packages/Pymakr/lib/pymakr-view.js:56:15)
```

### Commands

```
     -1:38.8.0 application:new-file (textarea.xterm-helper-textarea)
     -1:36.1.0 editor:newline (input.hidden-input)
     -1:34.1.0 core:move-left (input.hidden-input)
     -1:19.7.0 core:save (input.hidden-input)
     -1:03.4.0 application:new-file (input.hidden-input)
     -0:20.1.0 core:paste (textarea.xterm-helper-textarea)
     -0:09.6.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
Pymakr 0.9.3 
```

**Comment by RalphHogenbirk** [comment]
Solved with commit #c2ffc01 that was pushed to develop today. It's now possible to run a file without saving it. It'll get the content from the atom buffer.
