### ISSUE TITLE
Reset after FTP upload does not start boot.py/main.py

### ISSUE THREAD

**Issue by hallard** [pycom/pymakr-atom#82]
Hi there,
I think this is more an misunderstanding than an issue but I tried all parameters and can't solve it.
When I upload with the pymakr plugins everything works fine and upload is done. Then the board reset but at this point, stays in python console mode and thus the board firmware is not starting (boot.py). The workaround is to reset the board with it reset button and then it starts and works well.

Here the log from atom pymakr plugins (connected with FTP)
```
Uploading project (main folder)...
Safe booting device... (see settings for more info)

Reading file status
[1/1] Writing file main.py
Upload done, resetting board...
Connecting on 192.168.1.207...
Connection error: Error: Login timed out
Connecting on 192.168.1.207...
```

and the one from a FTDI connected to the RX/TX of the Lopy

````
>>> 
PYB: soft reboot
MicroPython v1.8.6-849-83e2f7f on 2018-03-19; LoPy with ESP32
Type "help()" for more information.
>>> 
>>> 
raw REPL; CTRL-B to exit
>OK5b5b22626f6f742e7079222c2266323765
...
...
5306365336166225d5d>OK>OK>OK>OK>OK>OK>OK>OK>OK>OK>OK>OK>OK>OK>OK>OK>OKets Jun  8 2016 00:22:57

rst:0x7 (TG0WDT_SYS_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff8028,len:8
load:0x3fff8030,len:1728
load:0x4009fa00,len:0
load:0x4009fa00,len:14584
entry 0x400a059c
MicroPython v1.8.6-849-83e2f7f on 2018-03-19; LoPy with ESP32
Type "help()" for more information.
>>> 
````

As you can see, looks like device stays in micropython, and does not run `boot.py`

Then I press reset button and

```
,kEv0,\Ev0,Ev0,.:p_d.Wxb}rv'A0닕iDIck:C!+:0f02ɕn:*H:00BCהQ
!+0xʲA0+i0!+i0fXbl5HrQ0XcC                       :a0bbnL
Device starting...
Scanning for known wifi nets
Connected to CH2I-HOTSPOT
device IP address : 192.168.1.207
IC2 Scan
[]
Starting LoRaWAN
joining
Joined in 8.400145 s
Sending LORA Packet
```
And it works

here my pymakr config

![image](https://user-images.githubusercontent.com/2471931/40580113-61fd7296-6138-11e8-8565-f0d14d6f81f9.png)

What I'm doing wrong?

**Comment by pedroknup** [comment]
Fixed on Pymakr 2.0
