### ISSUE TITLE
pymakr not install in atom 1.27.2

### ISSUE THREAD

**Issue by juanfc** [pycom/pymakr-atom#83]
Hi, need install pymakr!
![captura de pantalla de 2018-06-04 13-17-47](https://user-images.githubusercontent.com/5288836/40929009-b79ec660-67f9-11e8-9775-5bd4bd2506f8.png)

**Comment by PAS43** [comment]
+1

**Comment by JamesMcCarthy79** [comment]
yes needed this today for remote fix grrr

**Comment by CombatWombat27** [comment]
+1

**Comment by RalphHogenbirk** [comment]
Thanks for reporting guys. Pymakr v1.3.3 was just released to support Atom v1.27.2.

**Comment by juanfc** [comment]
thanks !!!
