### ISSUE TITLE
Pymakr console doesn't support copy paste

### ISSUE THREAD

**Issue by danicampora** [pycom/pymakr-atom#9]
This is a basic and must have feature. It needs to be implemented ASAP :-)

**Comment by RalphHogenbirk** [comment]
It works with ctrl-c and ctrl-v instead of cmd on mac (see readme). The cmd key somehow doesn't trigger a key command in the terminal. It's on my list to figure out, but since it works fine like this as well, it's not considered high prio at the moment.

**Comment by danicampora** [comment]
@RalphHogenbirk OK, but still it needs to be fixed on Mac OS as it's counter intuitive to use ctrl-c instead of cmd-c.

**Comment by RalphHogenbirk** [comment]
cmd support for copy paste is now added as of commit cbc513b
