### ISSUE TITLE
Installing/updating pymakr 1.4.3 failed; msbuild.exe to blame?

### ISSUE THREAD

**Issue by eymas** [pycom/pymakr-atom#99]
It's been bugging me for a while, but I cannot update nor (re)install the latest version of the plugin. From what I can gather it seems to break upon calling msbuild.exe, although I haven't gotten much success in figuring out exactly why. Installing the previous version went without any hassle.
I'll make an attempt at reinstalling each component (python, atom et cetera.) in the meantime.

Here's the full log below:
`
> serialport@6.2.2 install C:\Users\Tom\AppData\Local\Temp\apm-install-dir-118830-4792-tpq184.e6mdl\node_modules\pymakr\node_modules\serialport
> prebuild-install || node-gyp rebuild
C:\Users\Tom\AppData\Local\Temp\apm-install-dir-118830-4792-tpq184.e6mdl\node_modules\pymakr\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\Tom\AppData\Local\Temp\apm-install-dir-118830-4792-tpq184.e6mdl\node_modules\pymakr\node_modules\serialport\build\binding.sln]
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated parser-cctalk@1.0.2: reanmed to @serialport/parser-cctalk
npm WARN deprecated parser-byte-length@1.0.2: renamed to @serialport/parser-byte-length
npm WARN deprecated parser-readline@1.0.2: reanmed to @serialport/parser-readline
npm WARN deprecated parser-delimiter@1.0.2: reanmed to @serialport/parser-delimiter
npm WARN deprecated parser-ready@1.0.2: reanmed to @serialport/parser-ready
npm WARN deprecated parser-regex@1.0.2: reanmed to @serialport/parser-regex
prebuild-install WARN install No prebuilt binaries found (target=2.0.7 runtime=electron arch=x64 platform=win32)
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\Tom\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'C:\\Users\\Tom\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher 
gyp verb check python launcher python executable found: "C:\\Python27\\python.exe"
gyp verb check python version `C:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.15\r\n"
gyp verb get node dir compiling against --target node version: 2.0.7
gyp verb command install [ '2.0.7' ]
gyp verb install input version string "2.0.7"
gyp verb install installing version: iojs-2.0.7
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: iojs-2.0.7
gyp verb build dir attempting to create "build" dir: C:\Users\Tom\AppData\Local\Temp\apm-install-dir-118830-4792-tpq184.e6mdl\node_modules\pymakr\node_modules\serialport\build
gyp verb build dir "build" dir needed to be created? C:\Users\Tom\AppData\Local\Temp\apm-install-dir-118830-4792-tpq184.e6mdl\node_modules\pymakr\node_modules\serialport\build
gyp verb build/config.gypi creating config file
gyp sill build/config.gypi { target_defaults: 
gyp sill build/config.gypi    { cflags: [],
gyp sill build/config.gypi      default_configuration: 'Release',
gyp sill build/config.gypi      defines: [],
gyp sill build/config.gypi      include_dirs: [],
gyp sill build/config.gypi      libraries: [] },
gyp sill build/config.gypi   variables: 
gyp sill build/config.gypi    { asan: 0,
gyp sill build/config.gypi      coverage: false,
gyp sill build/config.gypi      debug_devtools: 'node',
gyp sill build/config.gypi      debug_http2: false,
gyp sill build/config.gypi      debug_nghttp2: false,
gyp sill build/config.gypi      force_dynamic_crt: 0,
gyp sill build/config.gypi      host_arch: 'x64',
gyp sill build/config.gypi      icu_data_file: 'icudt59l.dat',
gyp sill build/config.gypi      icu_data_in: '..\\..\\deps/icu-small\\source/data/in\\icudt59l.dat',
gyp sill build/config.gypi      icu_endianness: 'l',
gyp sill build/config.gypi      icu_gyp_path: 'tools/icu/icu-generic.gyp',
gyp sill build/config.gypi      icu_locales: 'en,root',
gyp sill build/config.gypi      icu_path: 'deps/icu-small',
gyp sill build/config.gypi      icu_small: true,
gyp sill build/config.gypi      icu_ver_major: '59',
gyp sill build/config.gypi      node_byteorder: 'little',
gyp sill build/config.gypi      node_enable_d8: false,
gyp sill build/config.gypi      node_enable_v8_vtunejit: false,
gyp sill build/config.gypi      node_install_npm: true,
gyp sill build/config.gypi      node_module_version: 57,
gyp sill build/config.gypi      node_no_browser_globals: false,
gyp sill build/config.gypi      node_prefix: '/usr/local',
gyp sill build/config.gypi      node_release_urlbase: 'https://nodejs.org/download/release/',
gyp sill build/config.gypi      node_shared: false,
gyp sill build/config.gypi      node_shared_cares: false,
gyp sill build/config.gypi      node_shared_http_parser: false,
gyp sill build/config.gypi      node_shared_libuv: false,
gyp sill build/config.gypi      node_shared_openssl: false,
gyp sill build/config.gypi      node_shared_zlib: false,
gyp sill build/config.gypi      node_tag: '',
gyp sill build/config.gypi      node_use_bundled_v8: true,
gyp sill build/config.gypi      node_use_dtrace: false,
gyp sill build/config.gypi      node_use_etw: true,
gyp sill build/config.gypi      node_use_lttng: false,
gyp sill build/config.gypi      node_use_openssl: true,
gyp sill build/config.gypi      node_use_perfctr: true,
gyp sill build/config.gypi      node_use_v8_platform: true,
gyp sill build/config.gypi      node_without_node_options: false,
gyp sill build/config.gypi      openssl_fips: '',
gyp sill build/config.gypi      openssl_no_asm: 0,
gyp sill build/config.gypi      shlib_suffix: 'so.57',
gyp sill build/config.gypi      target_arch: 'x64',
gyp sill build/config.gypi      v8_enable_gdbjit: 0,
gyp sill build/config.gypi      v8_enable_i18n_support: 1,
gyp sill build/config.gypi      v8_enable_inspector: 1,
gyp sill build/config.gypi      v8_no_strict_aliasing: 1,
gyp sill build/config.gypi      v8_optimized_debug: 0,
gyp sill build/config.gypi      v8_promise_internal_field_count: 1,
gyp sill build/config.gypi      v8_random_seed: 0,
gyp sill build/config.gypi      v8_trace_maps: 0,
gyp sill build/config.gypi      v8_use_snapshot: true,
gyp sill build/config.gypi      want_separate_host_toolset: 0,
gyp sill build/config.gypi      nodedir: 'C:\\Users\\Tom\\.atom\\.node-gyp\\.node-gyp\\iojs-2.0.7',
gyp sill build/config.gypi      copy_dev_lib: true,
gyp sill build/config.gypi      standalone_static_library: 1,
gyp sill build/config.gypi      access: '',
gyp sill build/config.gypi      allow_same_version: '',
gyp sill build/config.gypi      also: '',
gyp sill build/config.gypi      always_auth: '',
gyp sill build/config.gypi      audit: 'true',
gyp sill build/config.gypi      auth_type: 'legacy',
gyp sill build/config.gypi      bin_links: 'true',
gyp sill build/config.gypi      browser: '',
gyp sill build/config.gypi      ca: '',
gyp sill build/config.gypi      cache: 'C:\\Users\\Tom\\.atom\\.apm',
gyp sill build/config.gypi      cache_lock_retries: '10',
gyp sill build/config.gypi      cache_lock_stale: '60000',
gyp sill build/config.gypi      cache_lock_wait: '10000',
gyp sill build/config.gypi      cache_max: 'Infinity',
gyp sill build/config.gypi      cache_min: '10',
gyp sill build/config.gypi      cert: '',
gyp sill build/config.gypi      cidr: '',
gyp sill build/config.gypi      color: 'true',
gyp sill build/config.gypi      commit_hooks: 'true',
gyp sill build/config.gypi      depth: 'Infinity',
gyp sill build/config.gypi      description: 'true',
gyp sill build/config.gypi      dev: '',
gyp sill build/config.gypi      dist_url: 'https://atom.io/download/electron',
gyp sill build/config.gypi      dry_run: '',
gyp sill build/config.gypi      editor: 'notepad.exe',
gyp sill build/config.gypi      engine_strict: '',
gyp sill build/config.gypi      fetch_retries: '2',
gyp sill build/config.gypi      fetch_retry_factor: '10',
gyp sill build/config.gypi      fetch_retry_maxtimeout: '60000',
gyp sill build/config.gypi      fetch_retry_mintimeout: '10000',
gyp sill build/config.gypi      force: '',
gyp sill build/config.gypi      git: 'git',
gyp sill build/config.gypi      git_tag_version: 'true',
gyp sill build/config.gypi      global: '',
gyp sill build/config.gypi      globalconfig: 'C:\\Users\\Tom\\.atom\\.apm\\.apmrc',
gyp sill build/config.gypi      globalignorefile: 'C:\\Users\\Tom\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\bin\\etc\\npmignore',
gyp sill build/config.gypi      global_style: 'true',
gyp sill build/config.gypi      group: '',
gyp sill build/config.gypi      ham_it_up: '',
gyp sill build/config.gypi      heading: 'npm',
gyp sill build/config.gypi      https_proxy: '',
gyp sill build/config.gypi      if_present: '',
gyp sill build/config.gypi      ignore_prepublish: '',
gyp sill build/config.gypi      ignore_scripts: '',
gyp sill build/config.gypi      init_author_email: '',
gyp sill build/config.gypi      init_author_name: '',
gyp sill build/config.gypi      init_author_url: '',
gyp sill build/config.gypi      init_license: 'ISC',
gyp sill build/config.gypi      init_module: 'C:\\Users\\Tom\\.atom\\.node-gyp\\.npm-init.js',
gyp sill build/config.gypi      init_version: '1.0.0',
gyp sill build/config.gypi      json: '',
gyp sill build/config.gypi      key: '',
gyp sill build/config.gypi      legacy_bundling: '',
gyp sill build/config.gypi      link: '',
gyp sill build/config.gypi      local_address: '',
gyp sill build/config.gypi      logs_max: '10',
gyp sill build/config.gypi      long: '',
gyp sill build/config.gypi      maxsockets: '50',
gyp sill build/config.gypi      message: '%s',
gyp sill build/config.gypi      metrics_registry: 'https://registry.npmjs.org/',
gyp sill build/config.gypi      node_gyp: 'C:\\Users\\Tom\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\bin\\\\..\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp sill build/config.gypi      node_options: '',
gyp sill build/config.gypi      node_version: '8.9.3',
gyp sill build/config.gypi      no_proxy: '',
gyp sill build/config.gypi      offline: '',
gyp sill build/config.gypi      onload_script: '',
gyp sill build/config.gypi      only: '',
gyp sill build/config.gypi      optional: 'true',
gyp sill build/config.gypi      otp: '',
gyp sill build/config.gypi      package_lock: 'true',
gyp sill build/config.gypi      package_lock_only: '',
gyp sill build/config.gypi      parseable: '',
gyp sill build/config.gypi      prefer_offline: '',
gyp sill build/config.gypi      prefer_online: '',
gyp sill build/config.gypi      prefix: 'C:\\Users\\Tom\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\bin',
gyp sill build/config.gypi      production: 'true',
gyp sill build/config.gypi      progress: '',
gyp sill build/config.gypi      read_only: '',
gyp sill build/config.gypi      rebuild_bundle: 'true',
gyp sill build/config.gypi      registry: 'https://registry.npmjs.org/',
gyp sill build/config.gypi      rollback: 'true',
gyp sill build/config.gypi      runtime: 'electron',
gyp sill build/config.gypi      save: 'true',
gyp sill build/config.gypi      save_bundle: '',
gyp sill build/config.gypi      save_dev: '',
gyp sill build/config.gypi      save_exact: '',
gyp sill build/config.gypi      save_optional: '',
gyp sill build/config.gypi      save_prefix: '^',
gyp sill build/config.gypi      save_prod: '',
gyp sill build/config.gypi      scope: '',
gyp sill build/config.gypi      scripts_prepend_node_path: 'warn-only',
gyp sill build/config.gypi      script_shell: '',
gyp sill build/config.gypi      searchexclude: '',
gyp sill build/config.gypi      searchlimit: '20',
gyp sill build/config.gypi      searchopts: '',
gyp sill build/config.gypi      searchstaleness: '900',
gyp sill build/config.gypi      send_metrics: '',
gyp sill build/config.gypi      shell: 'C:\\Windows\\system32\\cmd.exe',
gyp sill build/config.gypi      shrinkwrap: 'true',
gyp sill build/config.gypi      sign_git_commit: '',
gyp sill build/config.gypi      sign_git_tag: '',
gyp sill build/config.gypi      sso_poll_frequency: '500',
gyp sill build/config.gypi      sso_type: 'oauth',
gyp sill build/config.gypi      strict_ssl: 'true',
gyp sill build/config.gypi      tag: 'latest',
gyp sill build/config.gypi      tag_version_prefix: 'v',
gyp sill build/config.gypi      target: '2.0.7',
gyp sill build/config.gypi      timing: '',
gyp sill build/config.gypi      tmp: 'C:\\Users\\Tom\\AppData\\Local\\Temp',
gyp sill build/config.gypi      umask: '0000',
gyp sill build/config.gypi      unicode: '',
gyp sill build/config.gypi      unsafe_perm: 'true',
gyp sill build/config.gypi      update_notifier: 'true',
gyp sill build/config.gypi      usage: '',
gyp sill build/config.gypi      user: '',
gyp sill build/config.gypi      userconfig: 'C:\\Users\\Tom\\.atom\\.apmrc',
gyp sill build/config.gypi      user_agent: 'npm/6.2.0 node/v8.9.3 win32 x64',
gyp sill build/config.gypi      version: '',
gyp sill build/config.gypi      versions: '',
gyp sill build/config.gypi      viewer: 'browser' } }
gyp verb build/config.gypi writing out config file: C:\Users\Tom\AppData\Local\Temp\apm-install-dir-118830-4792-tpq184.e6mdl\node_modules\pymakr\node_modules\serialport\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\Tom\AppData\Local\Temp\apm-install-dir-118830-4792-tpq184.e6mdl\node_modules\pymakr\node_modules\serialport\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\Tom\AppData\Local\Temp\apm-install-dir-118830-4792-tpq184.e6mdl\node_modules\pymakr\node_modules\serialport\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\Tom\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Tom\\AppData\\Local\\Temp\\apm-install-dir-118830-4792-tpq184.e6mdl\\node_modules\\pymakr\\node_modules\\serialport\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Tom\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Tom\\.atom\\.node-gyp\\.node-gyp\\iojs-2.0.7\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Tom\\.atom\\.node-gyp\\.node-gyp\\iojs-2.0.7',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Tom\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Tom\\AppData\\Local\\Temp\\apm-install-dir-118830-4792-tpq184.e6mdl\\node_modules\\pymakr\\node_modules\\serialport',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Tom\\AppData\\Local\\Temp\\apm-install-dir-118830-4792-tpq184.e6mdl\\node_modules\\pymakr\\node_modules\\serialport\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\Tom\.atom\.node-gyp\.node-gyp\iojs-2.0.7
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry 
gyp verb "Release" dir needed to be created? null
gyp verb copying "iojs.lib" for x64 C:\Users\Tom\.atom\.node-gyp\.node-gyp\iojs-2.0.7\Release\iojs.lib
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Tom\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\Tom\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Tom\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Tom\AppData\Local\Temp\apm-install-dir-118830-4792-tpq184.e6mdl\node_modules\pymakr\node_modules\serialport
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Tom\AppData\Local\Temp\apm-install-dir-118830-4792-tpq184.e6mdl\package.json'
npm WARN apm-install-dir-118830-4792-tpq184.e6mdl No description
npm WARN apm-install-dir-118830-4792-tpq184.e6mdl No repository field.
npm WARN apm-install-dir-118830-4792-tpq184.e6mdl No README data
npm WARN apm-install-dir-118830-4792-tpq184.e6mdl No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@6.2.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@6.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tom\.atom\.apm\_logs\2018-09-30T12_02_21_200Z-debug.log`

**Comment by stefanbrudny** [comment]
Same here, I must say I am really fed up with atom / pymakr / npm / ms never working.  Versions same, clean install. 

gyp verb "Release" dir needed to be created? null
gyp verb copying "iojs.lib" for x64 C:\Users\stefan\.atom\.node-gyp\.node-gyp\iojs-2.0.7\Release\iojs.lib
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\stefan\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\stefan\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\stefan\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\stefan\AppData\Local\Temp\apm-install-dir-118830-28632-uhaav8.beuf\node_modules\pymakr\node_modules\serialport
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by RalphHogenbirk** [comment]
Hi. It seems like a few others are struggling with this on 1.4.3. I've spotted the mistake, which is that the serialport dependancy shouldn't even be in the package.json since it fails on most windows machines (as seen in your stacktraces). On windows it always falls back to the included precompiled version of serialport.

I've just released 1.4.4 with this small fix. Please let me know if this solves your issues.

**Comment by eymas** [comment]
> 
> 
> Hi. It seems like a few others are struggling with this on 1.4.3. I've spotted the mistake, which is that the serialport dependancy shouldn't even be in the package.json since it fails on most windows machines (as seen in your stacktraces). On windows it always falls back to the included precompiled version of serialport.
> 
> I've just released 1.4.4 with this small fix. Please let me know if this solves your issues.

Yes it has, v1.4.4 installed successfully through apm and I've tested it by making & uploading some testing code to a LoPy4.
Glad to hear the mistake was spotted quickly and thanks for the response!
